# Generated by Django 3.0.5 on 2021-02-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_answer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
