# Generated by Django 3.0.5 on 2021-02-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20210221_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questionnaire',
            new_name='Survey',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionnaire',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='surveytoken',
            old_name='questionnaire',
            new_name='survey',
        ),
    ]
