# Generated by Django 3.0.5 on 2021-02-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_auto_20210224_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='surevy_token',
        ),
    ]
