# Generated by Django 3.0.5 on 2021-02-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_answer_survey_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='answers_sent',
            field=models.BooleanField(default=False),
        ),
    ]
